name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - name: "Say hello to Nimish"
        run: echo "$name to $myname"
        env:
          myname: Nimish